source "https://rubygems.org"
gem "rspec"
gem "hashie"
gem "sinatra", "1.4.4"
gem "octokit", "~> 2.0"
gem "awesome_print", :git => "https://github.com/awesome-print/awesome_print.git", :branch +> "1.8.0" 
gem "pry", :group => "development"
